FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y git ca-certificates && apt-get clean

ARG FASTRG_REF=master
RUN git clone --branch "${FASTRG_REF}" --recurse-submodules \
        https://github.com/FastResidentialGateway/fastrg-node.git /tmp/fastrg-src

RUN /tmp/fastrg-src/essentials.sh
RUN /tmp/fastrg-src/boot.sh --env-only
RUN rm -rf /tmp/fastrg-src
